### ISSUE TITLE
'/uploads' does not show any lists

### ISSUE THREAD

**Issue by mzch** [femto-apps/web-file-uploader#28]
When I visited `https://upldr.info/uploads`, my uploads were not shown and web-file-uploader reports an error as below:

```
Sep 19 21:46:44 ls node[7639]: #033[0mGET /uploads #033[32m200#033[0m 174.350 ms - -#033[0m
Sep 19 21:46:44 ls node[28725]: GET ?token=9d1f06d3-811a-4de9-828c-5c3da49df960 : getAsync 0.2ms
Sep 19 21:46:44 ls node[28725]: GET ?token=9d1f06d3-811a-4de9-828c-5c3da49df960 : getReq 0.37ms
Sep 19 21:46:44 ls node[7639]: #033[0mGET /css/main.css #033[32m200#033[0m 20.479 ms - 380#033[0m
Sep 19 21:46:44 ls node[7639]: Generating thumb for 5f66db8c110b3d751832911e
Sep 19 21:46:44 ls node[7639]: (node:7639) UnhandledPromiseRejectionWarning: S3Error: The specified bucket does not exist
Sep 19 21:46:44 ls node[7639]:     at Object.parseError (/srv/webfile/web-file-uploader/node_modules/minio/dist/main/xml-parsers.js:86:11)
Sep 19 21:46:44 ls node[7639]:     at /srv/webfile/web-file-uploader/node_modules/minio/dist/main/transformers.js:156:22
Sep 19 21:46:44 ls node[7639]:     at DestroyableTransform._flush (/srv/webfile/web-file-uploader/node_modules/minio/dist/main/transformers.js:80:10)
Sep 19 21:46:44 ls node[7639]:     at DestroyableTransform.prefinish (/srv/webfile/web-file-uploader/node_modules/readable-stream/lib/_stream_transform.js:138:10)
Sep 19 21:46:44 ls node[7639]:     at DestroyableTransform.emit (events.js:315:20)
Sep 19 21:46:44 ls node[7639]:     at prefinish (/srv/webfile/web-file-uploader/node_modules/readable-stream/lib/_stream_writable.js:619:14)
Sep 19 21:46:44 ls node[7639]:     at finishMaybe (/srv/webfile/web-file-uploader/node_modules/readable-stream/lib/_stream_writable.js:627:5)
Sep 19 21:46:44 ls node[7639]:     at endWritable (/srv/webfile/web-file-uploader/node_modules/readable-stream/lib/_stream_writable.js:638:3)
Sep 19 21:46:44 ls node[7639]:     at DestroyableTransform.Writable.end (/srv/webfile/web-file-uploader/node_modules/readable-stream/lib/_stream_writable.js:594:41)
Sep 19 21:46:44 ls node[7639]:     at IncomingMessage.onend (_stream_readable.js:681:10)
Sep 19 21:46:44 ls node[7639]:     at Object.onceWrapper (events.js:421:28)
Sep 19 21:46:44 ls node[7639]:     at IncomingMessage.emit (events.js:327:22)
Sep 19 21:46:44 ls node[7639]:     at endReadableNT (_stream_readable.js:1220:12)
Sep 19 21:46:44 ls node[7639]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Sep 19 21:46:44 ls node[7639]: (node:7639) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Sep 19 21:46:44 ls node[7639]: (node:7639) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Sep 19 21:46:44 ls node[28725]: GET ?token=9d1f06d3-811a-4de9-828c-5c3da49df960 : getAsync 0.19ms
Sep 19 21:46:44 ls node[28725]: GET ?token=9d1f06d3-811a-4de9-828c-5c3da49df960 : getReq 0.37ms
Sep 19 21:46:44 ls node[7639]: #033[0mGET /sgca.png #033[32m200#033[0m 15.512 ms - 76171#033[0m
Sep 19 21:46:44 ls node[28725]: GET ?token=9d1f06d3-811a-4de9-828c-5c3da49df960 : getAsync 0.19ms
Sep 19 21:46:44 ls node[28725]: GET ?token=9d1f06d3-811a-4de9-828c-5c3da49df960 : getReq 0.4ms
Sep 19 21:46:44 ls node[7639]: #033[0mGET /sgca.png #033[32m200#033[0m 29.617 ms - 76171#033[0m
```

When access directly to `https://upldr.info/sgca`, the uploaded picture is shown correctly.

Any idean?

**Comment by mzch** [comment]
I found Web-File-Uploader needs undocumented bucket `items`.
This fix includes my PR #29

**Comment by popey456963** [comment]
Can we close, as #29 has been merged?

**Comment by mzch** [comment]
Yes, thanks!
